[2024-04-29T07:23:42.781+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T07:23:42.794+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T00:36:00+00:00 [queued]>
[2024-04-29T07:23:42.799+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T00:36:00+00:00 [queued]>
[2024-04-29T07:23:42.800+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-29T07:23:42.810+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-04-29 00:36:00+00:00
[2024-04-29T07:23:42.815+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=754) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T07:23:42.816+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'transform_load_weather_data', 'scheduled__2024-04-29T00:36:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmpy49dzj2t']
[2024-04-29T07:23:42.817+0000] {standard_task_runner.py:63} INFO - Started process 760 to run task
[2024-04-29T07:23:42.817+0000] {standard_task_runner.py:91} INFO - Job 118: Subtask transform_load_weather_data
[2024-04-29T07:23:42.852+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T00:36:00+00:00 [running]> on host 6dbc7f679521
[2024-04-29T07:23:42.916+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T00:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T00:36:00+00:00'
[2024-04-29T07:23:42.918+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T07:23:42.919+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T07:23:42.919+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_open_weather() missing 1 required positional argument: 'task_'
[2024-04-29T07:23:42.927+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_for_open_weather, task_id=transform_load_weather_data, execution_date=20240429T003600, start_date=20240429T072342, end_date=20240429T072342
[2024-04-29T07:23:42.938+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 118 for task transform_load_weather_data (get_open_weather() missing 1 required positional argument: 'task_'; 760)
[2024-04-29T07:23:42.951+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T07:23:43.015+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T07:23:43.017+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
