[2024-04-29T07:27:48.781+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T07:27:48.801+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T02:48:00+00:00 [queued]>
[2024-04-29T07:27:48.811+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T02:48:00+00:00 [queued]>
[2024-04-29T07:27:48.812+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T07:27:48.828+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-04-29 02:48:00+00:00
[2024-04-29T07:27:48.837+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1527) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T07:27:48.839+0000] {standard_task_runner.py:63} INFO - Started process 1546 to run task
[2024-04-29T07:27:48.839+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'transform_load_weather_data', 'scheduled__2024-04-29T02:48:00+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmp94d2j28r']
[2024-04-29T07:27:48.840+0000] {standard_task_runner.py:91} INFO - Job 357: Subtask transform_load_weather_data
[2024-04-29T07:27:48.907+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T02:48:00+00:00 [running]> on host 6dbc7f679521
[2024-04-29T07:27:49.024+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T02:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T02:48:00+00:00'
[2024-04-29T07:27:49.029+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T07:27:49.030+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T07:27:49.033+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_open_weather() missing 1 required positional argument: 'task_'
[2024-04-29T07:27:49.046+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_for_open_weather, task_id=transform_load_weather_data, execution_date=20240429T024800, start_date=20240429T072748, end_date=20240429T072749
[2024-04-29T07:27:49.063+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 357 for task transform_load_weather_data (get_open_weather() missing 1 required positional argument: 'task_'; 1546)
[2024-04-29T07:27:49.098+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T07:27:49.225+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T07:27:49.228+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
