[2024-04-29T07:26:17.366+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T07:26:17.384+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T01:40:00+00:00 [queued]>
[2024-04-29T07:26:17.392+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T01:40:00+00:00 [queued]>
[2024-04-29T07:26:17.393+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-29T07:26:17.403+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-04-29 01:40:00+00:00
[2024-04-29T07:26:17.409+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1182) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T07:26:17.411+0000] {standard_task_runner.py:63} INFO - Started process 1196 to run task
[2024-04-29T07:26:17.411+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'transform_load_weather_data', 'scheduled__2024-04-29T01:40:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmp_doqggsj']
[2024-04-29T07:26:17.412+0000] {standard_task_runner.py:91} INFO - Job 251: Subtask transform_load_weather_data
[2024-04-29T07:26:17.446+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T01:40:00+00:00 [running]> on host 6dbc7f679521
[2024-04-29T07:26:17.509+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T01:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T01:40:00+00:00'
[2024-04-29T07:26:17.510+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T07:26:17.510+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T07:26:17.511+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_open_weather() missing 1 required positional argument: 'task_'
[2024-04-29T07:26:17.517+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_for_open_weather, task_id=transform_load_weather_data, execution_date=20240429T014000, start_date=20240429T072617, end_date=20240429T072617
[2024-04-29T07:26:17.528+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 251 for task transform_load_weather_data (get_open_weather() missing 1 required positional argument: 'task_'; 1196)
[2024-04-29T07:26:17.544+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T07:26:17.555+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T07:26:17.557+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
