[2024-04-29T07:26:35.871+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T07:26:35.884+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T02:28:00+00:00 [queued]>
[2024-04-29T07:26:35.891+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T02:28:00+00:00 [queued]>
[2024-04-29T07:26:35.891+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T07:26:35.902+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-04-29 02:28:00+00:00
[2024-04-29T07:26:35.909+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1329) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T07:26:35.911+0000] {standard_task_runner.py:63} INFO - Started process 1350 to run task
[2024-04-29T07:26:35.911+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'transform_load_weather_data', 'scheduled__2024-04-29T02:28:00+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmpbwkm_avb']
[2024-04-29T07:26:35.912+0000] {standard_task_runner.py:91} INFO - Job 301: Subtask transform_load_weather_data
[2024-04-29T07:26:35.950+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T02:28:00+00:00 [running]> on host 6dbc7f679521
[2024-04-29T07:26:36.011+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T02:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T02:28:00+00:00'
[2024-04-29T07:26:36.012+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T07:26:36.013+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T07:26:36.013+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_open_weather() missing 1 required positional argument: 'task_'
[2024-04-29T07:26:36.019+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_for_open_weather, task_id=transform_load_weather_data, execution_date=20240429T022800, start_date=20240429T072635, end_date=20240429T072636
[2024-04-29T07:26:36.029+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 301 for task transform_load_weather_data (get_open_weather() missing 1 required positional argument: 'task_'; 1350)
[2024-04-29T07:26:36.044+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T07:26:36.056+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T07:26:36.058+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
